# -*- mode: ruby -*-
# vi: set ft=ruby :
$samplescript = <<SCRIPT
yum install -y httpd
systemctl enable httpd
systemctl start httpd
SCRIPT


Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "myhost"
  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.synced_folder "/e/Projects/Test1/test-git/Vagrant_Project/kubernetes", "/var/www/html"
  config.vm.provision "shell", inline: $samplescript
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "512"
    vb.cpus = "1"
  end
end
