Vagrant.configure("2") do |config|
	config.vm.define "master" do |master|
	  master.vm.box = "centos/7"
	  master.vm.network "private_network", ip: "192.168.10.21"
	  master.vm.hostname = "master"
    master.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
    master.vm.provision "shell", inline: <<-SHELL
      sudo echo "192.168.10.21 master" | sudo tee -a /etc/hosts
			sudo echo "192.168.10.22 node1" | sudo tee -a /etc/hosts
			sudo echo "192.168.10.23 node2" | sudo tee -a /etc/hosts
      #sudo yum update -y
    SHELL
  end
end