pipeline {
    agent { docker { image 'python:3.5.1' } }
    stages {
        stage('build') {
            steps {
                sh 'python --version'
            }
        }
        stage('test') {
            sh 'git clone https://github.com/prashdevlop/test-git.git -b Docker'
        }
    }
}